// Code generated by "stringer -type=side"; DO NOT EDIT.

package internal

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[top-0]
	_ = x[bottom-1]
}

const _side_name = "topbottom"

var _side_index = [...]uint8{0, 3, 9}

func (i side) String() string {
	if i < 0 || i >= side(len(_side_index)-1) {
		return "side(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _side_name[_side_index[i]:_side_index[i+1]]
}
